from __future__ import annotations

import asyncio
import json
import tempfile
import unittest
from datetime import datetime, timedelta, timezone
from pathlib import Path

from stategraph import Observation, StateCandidate, StateGraph
from stategraph.evaluation.checkpoint import (
    CHECKPOINT_SCHEMA_VERSION,
    CheckpointCorrupt,
    CheckpointManager,
    ResumeRejected,
    empty_snapshot,
    restore_repository_snapshot,
    snapshot_repository,
)
from stategraph.storage import InMemoryStateRepository


UTC = timezone.utc


def identity(**overrides: str) -> dict[str, str]:
    value = {
        'run_id': 'test-run',
        'case_id': 'test-case',
        'model_provider': 'OpenAI',
        'model_name': 'gpt-5-nano',
        'reasoning_effort': 'minimal',
        'input_hash': 'input-hash',
        'case_manifest_hash': 'manifest-hash',
        'config_hash': 'config-hash',
        'code_version': 'code-hash',
        'module1_freeze_digest': 'module1-hash',
        'module4_freeze_digest': 'module4-hash',
    }
    value.update(overrides)
    return value


def snapshot(extra: dict | None = None) -> dict:
    value = empty_snapshot()
    value['propagation_state'] = dict(extra or {})
    return value


def semantic_snapshot(value: dict) -> dict:
    """Compare meaning while ignoring UUIDs generated by separate processes."""

    states = []
    by_id: dict[str, tuple] = {}
    for row in value['state_nodes']:
        state = (
            row['entity'], row['attribute'], row['value_json'], row['status'],
            row['time_start'], row['time_end'], row['conditions_json'],
            row['observation_id'], row['observation_index'], row['sequence_index'],
        )
        by_id[row['state_id']] = state
        states.append(state)
    relations = []
    for row in value['relation_typing_results']:
        relations.append((
            by_id.get(row['source_state_id']),
            by_id.get(row['target_state_id']),
            row['relation_type'],
            row.get('dependency_strength'),
            row.get('reason'),
        ))
    return {
        'states': sorted(states),
        'relations': sorted(relations, key=repr),
        'lifecycle': sorted(
            (item['status'] for item in value['lifecycle_state'])
        ),
        'propagation': value['propagation_state'],
    }


class CheckpointContractTests(unittest.TestCase):
    def test_no_checkpoint_starts_at_zero(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            manager = CheckpointManager(Path(directory) / 'checkpoint.json', identity=identity())
            self.assertEqual(manager.resume_position()['observation_index'], 0)

    def test_commit_prefix_resumes_at_next_observation(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            manager = CheckpointManager(Path(directory) / 'checkpoint.json', identity=identity())
            manager.mark_in_progress(0, 'obs-0')
            manager.commit_observation(0, 'obs-0', state_snapshot=snapshot())
            manager.mark_in_progress(1, 'obs-1')
            manager.commit_observation(1, 'obs-1', state_snapshot=snapshot())
            self.assertEqual(manager.resume_position()['observation_index'], 2)

    def test_partial_observation_is_rerun_not_committed(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'checkpoint.json'
            manager = CheckpointManager(path, identity=identity())
            manager.mark_in_progress(0, 'obs-0')
            manager.commit_observation(0, 'obs-0', state_snapshot=snapshot())
            manager.mark_in_progress(1, 'obs-1')
            resumed = CheckpointManager(path, identity=identity()).resume_position()
            self.assertEqual(resumed['status'], 'IN_PROGRESS')
            self.assertEqual(resumed['observation_index'], 1)
            self.assertEqual(resumed['completed_observation_ids'], ['obs-0'])

    def test_corrupted_checkpoint_fails_closed(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'checkpoint.json'
            path.write_text('{', encoding='utf-8')
            with self.assertRaises(CheckpointCorrupt):
                CheckpointManager(path, identity=identity()).load()

    def test_wrong_input_model_and_config_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'checkpoint.json'
            manager = CheckpointManager(path, identity=identity())
            manager.create_or_load()
            for change in ({'input_hash': 'different'}, {'model_name': 'other'}, {'config_hash': 'different'}):
                with self.assertRaises(ResumeRejected):
                    CheckpointManager(path, identity=identity(**change)).validate_resume()

    def test_case_provider_and_freeze_mismatches_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'checkpoint.json'
            manager = CheckpointManager(path, identity=identity())
            manager.create_or_load()
            for change in (
                {'case_id': 'different'},
                {'model_provider': 'different'},
                {'module1_freeze_digest': 'different'},
                {'module4_freeze_digest': 'different'},
            ):
                with self.assertRaises(ResumeRejected):
                    CheckpointManager(path, identity=identity(**change)).validate_resume()

    def test_incompatible_schema_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            with self.assertRaises(ValueError):
                CheckpointManager(
                    Path(directory) / 'checkpoint.json',
                    identity=identity(),
                    schema_version=CHECKPOINT_SCHEMA_VERSION + 1,
                )

    def test_duplicate_commit_has_no_semantic_duplication(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            manager = CheckpointManager(Path(directory) / 'checkpoint.json', identity=identity())
            manager.mark_in_progress(0, 'obs-0')
            first = manager.commit_observation(0, 'obs-0', state_snapshot=snapshot())
            second = manager.commit_observation(0, 'obs-0', state_snapshot=snapshot())
            self.assertEqual(first['completed_observation_ids'], ['obs-0'])
            self.assertEqual(second['completed_observation_ids'], ['obs-0'])

    def test_interrupted_temp_write_leaves_previous_checkpoint_usable(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'checkpoint.json'
            manager = CheckpointManager(path, identity=identity())
            manager.create_or_load()
            path.with_name(f'.{path.name}.interrupted.tmp').write_text('{', encoding='utf-8')
            self.assertEqual(manager.load()['checkpoint_schema_version'], 1)


class CheckpointIntegrationTests(unittest.IsolatedAsyncioTestCase):
    async def test_restore_preserves_state_and_relations(self) -> None:
        source = InMemoryStateRepository()
        graph = StateGraph(repository=source)
        now = datetime(2030, 1, 1, tzinfo=UTC)
        first = await graph.ingest(
            Observation('Alice is available.', now, 'test', observation_id='obs-0', observation_index=0),
            candidates=(StateCandidate('Alice', 'availability', 'available'),),
        )
        second = await graph.ingest(
            Observation('Alice is unavailable.', now + timedelta(days=1), 'test', observation_id='obs-1', observation_index=1),
            candidates=(StateCandidate('Alice', 'availability', 'unavailable'),),
        )
        before = await snapshot_repository(source, 'default')
        restored = InMemoryStateRepository()
        await restore_repository_snapshot(restored, before)
        after = await snapshot_repository(restored, 'default')
        self.assertEqual(before, after)
        self.assertEqual(second.invalidated_state_ids, (first.states[0].state_id,))

    async def test_replace_restore_discards_uncommitted_observation(self) -> None:
        repository = InMemoryStateRepository()
        graph = StateGraph(repository=repository)
        now = datetime(2030, 1, 1, tzinfo=UTC)
        await graph.ingest(
            Observation('Alice is available.', now, 'test', observation_id='obs-0', observation_index=0),
            candidates=(StateCandidate('Alice', 'availability', 'available'),),
        )
        committed = await snapshot_repository(repository, 'default')
        await graph.ingest(
            Observation('Alice is unavailable.', now + timedelta(days=1), 'test', observation_id='obs-1', observation_index=1),
            candidates=(StateCandidate('Alice', 'availability', 'unavailable'),),
        )
        await restore_repository_snapshot(repository, committed, replace=True, group_id='default')
        restored = await snapshot_repository(repository, 'default')
        self.assertEqual(semantic_snapshot(committed), semantic_snapshot(restored))
        self.assertEqual({row['observation_id'] for row in restored['state_nodes']}, {'obs-0'})

    async def test_uninterrupted_and_resumed_semantic_state_are_equivalent(self) -> None:
        now = datetime(2030, 1, 1, tzinfo=UTC)
        observations = (
            Observation('Alice is available.', now, 'test', observation_id='obs-0', observation_index=0),
            Observation('Alice is unavailable.', now + timedelta(days=1), 'test', observation_id='obs-1', observation_index=1),
        )
        candidates = (
            StateCandidate('Alice', 'availability', 'available'),
            StateCandidate('Alice', 'availability', 'unavailable'),
        )

        uninterrupted_repo = InMemoryStateRepository()
        uninterrupted = StateGraph(repository=uninterrupted_repo)
        for observation, candidate in zip(observations, candidates, strict=True):
            await uninterrupted.ingest(observation, candidates=(candidate,))
        uninterrupted_snapshot = await snapshot_repository(uninterrupted_repo, 'default')
        uninterrupted_retrieval = await uninterrupted.retrieve('Alice availability')

        with tempfile.TemporaryDirectory() as directory:
            manager = CheckpointManager(Path(directory) / 'checkpoint.json', identity=identity())
            prefix_repo = InMemoryStateRepository()
            prefix_graph = StateGraph(repository=prefix_repo)
            manager.mark_in_progress(0, observations[0].observation_id)
            prefix_result = await prefix_graph.ingest(observations[0], candidates=(candidates[0],))
            prefix_snapshot = await snapshot_repository(prefix_repo, 'default', evidence_ids=(prefix_result.evidence.evidence_id,))
            manager.commit_observation(0, observations[0].observation_id, state_snapshot=prefix_snapshot)

            resumed_repo = InMemoryStateRepository()
            await restore_repository_snapshot(resumed_repo, manager.load()['state_snapshot'])
            resumed = StateGraph(repository=resumed_repo)
            manager.mark_in_progress(1, observations[1].observation_id)
            resumed_result = await resumed.ingest(observations[1], candidates=(candidates[1],))
            resumed_snapshot = await snapshot_repository(resumed_repo, 'default', evidence_ids=(resumed_result.evidence.evidence_id,))
            manager.commit_observation(1, observations[1].observation_id, state_snapshot=resumed_snapshot)
            resumed_retrieval = await resumed.retrieve('Alice availability')

        self.assertEqual(semantic_snapshot(uninterrupted_snapshot), semantic_snapshot(resumed_snapshot))
        self.assertEqual(uninterrupted_retrieval.grounded_context(), resumed_retrieval.grounded_context())

    async def test_committed_prefix_makes_zero_repeated_llm_calls(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'checkpoint.json'
            manager = CheckpointManager(path, identity=identity())
            calls: list[int] = []
            for index in range(2):
                calls.append(index)
                manager.mark_in_progress(index, f'obs-{index}')
                manager.commit_observation(index, f'obs-{index}', state_snapshot=snapshot())
            resumed = CheckpointManager(path, identity=identity()).resume_position()
            for index in range(resumed['observation_index'], 3):
                calls.append(index)
                manager.mark_in_progress(index, f'obs-{index}')
                manager.commit_observation(index, f'obs-{index}', state_snapshot=snapshot())
            self.assertEqual(calls, [0, 1, 2])
            self.assertEqual(calls[:2], [0, 1])

    async def test_fixed_prefix_integrations_for_mab_stale_and_v2(self) -> None:
        for label in ('mab-conflict', 'stale', 'longmemeval-v2'):
            with self.subTest(label=label), tempfile.TemporaryDirectory() as directory:
                manager = CheckpointManager(
                    Path(directory) / 'checkpoint.json',
                    identity=identity(run_id=label, case_id=f'{label}-fixed-prefix'),
                )
                manager.mark_in_progress(0, f'{label}-obs-0')
                manager.commit_observation(0, f'{label}-obs-0', state_snapshot=snapshot({'label': label}))
                resumed = CheckpointManager(
                    Path(directory) / 'checkpoint.json',
                    identity=identity(run_id=label, case_id=f'{label}-fixed-prefix'),
                ).resume_position()
                self.assertEqual(resumed['observation_index'], 1)
                self.assertEqual(resumed['completed_observation_ids'], [f'{label}-obs-0'])


if __name__ == '__main__':
    unittest.main()
